config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Defines the root path route ("/")
  # root "posts#index"
  root to: 'lists#index'
  resources :lists, only: ['index', 'show', 'new', 'create'] do
    resources :bookmarks, only: ['new', 'create']
    resources :reviews, only: ['create']
  end
  resources :bookmarks, only: ['destroy']
  resources :reviews, only: ['destroy']
  resources :lists, only: ['destroy']
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/bookmark.rb
class Bookmark < ApplicationRecord
  belongs_to :movie
  belongs_to :list
  validates :comment, length: { minimum: 6 }
  validates_uniqueness_of :movie_id, scope: :list_id
end

app/models/list.rb
class List < ApplicationRecord
  validates :name, uniqueness: true, presence: true
  validates :description, presence: true
  has_many :bookmarks, dependent: :destroy
  has_many :movies, through: :bookmarks, dependent: :destroy
  has_many :reviews, dependent: :destroy
end

app/models/movie.rb
class Movie < ApplicationRecord
  has_many :bookmarks
  validates :title, uniqueness: true, presence: true
  validates :overview, uniqueness: true, presence: true
end

app/models/review.rb
class Review < ApplicationRecord
  belongs_to :list
  validates :comment, presence: true
  validates :rating, presence: true, inclusion: { in: [1, 2, 3, 4, 5] }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/bookmarks_controller.rb
class BookmarksController < ApplicationController
  before_action :find_list, only: [:new, :create]
  def new
    @bookmark = Bookmark.new
  end

  def create
    @bookmark = Bookmark.new(bookmark_params)
    @bookmark.list = @list
    if @bookmark.save == true
      redirect_to list_path(@list)
    else
      render :new, status: :unprocessable_entity
    end
  end

  def destroy
    @bookmark = Bookmark.find(params[:id])
    @bookmark.destroy
    redirect_to list_path(@bookmark.list), status: :see_other
  end

  private

  def find_list
    @list = List.find(params[:list_id])
  end

  def bookmark_params
    params.require(:bookmark).permit(:movie_id, :comment)
  end
end

app/controllers/lists_controller.rb
class ListsController < ApplicationController
  def index
    @lists = List.all
  end

  def new
    @list = List.new
  end

  def create
    @list = List.new(list_params)
    if @list.save == true
      redirect_to list_path(@list)
    else
      render :new, status: :unprocessable_entity
    end
  end

  def show
    @list = List.find(params[:id])
    @bookmarks = @list.bookmarks
    @review = Review.new(list: @list)
  end

  def destroy
    @list = List.find(params[:id])
    @list.destroy
    redirect_to lists_path, status: :see_other
  end

  private
  def list_params
    params.require(:list).permit(:name, :description)
  end
end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController
  # before_action :find_list, only: [:new, :create]
  before_action :find_list, only: [:create]
  # def new
  #   @review = Review.new
  # end

  def create
    @review = Review.new(review_params)
    @review.list = @list
    if @review.save == true
      redirect_to list_path(@list)
    else
      render 'lists/show', status: :unprocessable_entity
    end
  end

  def destroy
    @review = Review.find(params[:id])
    @review.destroy
    @list = @review.list
    redirect_to list_path(@list)
  end

  private
  def review_params
    params.require(:review).permit(:comment, :rating)
  end

  def find_list
    @list = List.find(params[:list_id])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/bookmarks_helper.rb
module BookmarksHelper
end

app/helpers/lists_helper.rb
module ListsHelper
end

app/helpers/reviews_helper.rb
module ReviewsHelper
end

app/views/bookmarks/new.html.erb
<h1> Add movie to:<%= @list.name%></h3>
<%= simple_form_for [@list, @bookmark] do |f| %>
<%= f.input :comment%>
<%= f.association :movie %>
<%= f.submit 'Add movie'%>
<%end%>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsWatchList</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/lists/index.html.erb
<h1>All of your lists</h1>
<ul>
<% @lists.each do |list|%>
<div class="card-product">
  <img src="https://raw.githubusercontent.com/lewagon/fullstack-images/master/uikit/skateboard.jpg" />
  <div class="card-product-infos">
    <h2><%=link_to list.name, list_path(list)%></h2>
    <p><%= list.description%></p>
  </div>
</div>

<%end%>
</ul>

<h3>Create a new list!</h3>
<p><%= link_to "create movie list", new_list_path%></p>

app/views/lists/new.html.erb
<%= simple_form_for @list do |f| %>
<%= f.input :name %>
<%= f.input :description%>
<%= f.submit "Submit!"%>
<%end%>

app/views/lists/show.html.erb
<h1>Your list</h1>
<% @bookmarks.each do |bookmark|%>
  <p>The title of the movie is <%=bookmark.movie.title%> and the rating is <%=bookmark.movie.rating%></p>
  <p>Your comment is <%= bookmark.comment%></p>
  <%= link_to "remove bookmark", bookmark_path(bookmark), data: { turbo_method: :delete, turbo_confirm: "are you sure you want to YEET your bookmark" }%>
<%end%>
<div>
  <%= link_to "add a bookmark", new_list_bookmark_path(@list)%>
</div>
<%= link_to "back to all lists", lists_path%>
<div>
  <%=link_to "remove list", list_path(@list), data: { turbo_method: :delete, turbo_confirm: "are you sure you want to YEET your list" }%>
</div>
<h2>Add a review for this list</h2>
<%= simple_form_for [@list, @review] do |f| %>
  <%= f.input :comment%>
  <%= f.input :rating%>
  <%= f.submit 'Add Review'%>
<%end%>
<div>
<h3>All reviews</h3>
<% @list.reviews.each do |review|%>
  <p><%= review.comment%> and the rating is <%= "⭐" * review.rating%></p>
  <%= link_to "remove review", review_path(review), data: { turbo_method: :delete, turbo_confirm: "are you sure you want to YEET your review" }%>
<%end%>
</div>